In [40]:
import numpy as np
from sklearn.decomposition import PCA

In [41]:
X = np.array([[-1,-1,-1], 
              [-2,-1,-1], 
              [-3,-2,-1], 
              [1,1,1], 
              [2,1,1], 
              [3,2,1]])
pca = PCA(n_components=2)
pca.fit(X)

PCA(n_components=2)

In [42]:
pca.explained_variance_ratio_

array([0.97884237, 0.01586514])

In [43]:
pca.singular_values_

array([6.71019739, 0.85428136])

In [44]:
pca = PCA(n_components=2, svd_solver='full')
pca.fit(X)

PCA(n_components=2, svd_solver='full')

In [45]:
pca.explained_variance_ratio_

array([0.97884237, 0.01586514])

In [46]:
pca.singular_values_

array([6.71019739, 0.85428136])

In [ ]:
pca = PCA(n_components=2, svd_solver='arpack') 
# note with arpack n_components must be less than n_features
pca.fit(X)

PCA(n_components=2, svd_solver='arpack')

In [48]:
pca.explained_variance_ratio_

array([0.97884237, 0.01586514])

In [49]:
pca.singular_values_

array([6.71019739, 0.85428136])